#!/bin/bash

_INSTALL(){
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_101_EasyList/filter.txt -O /root/AdGuardHome/data/filters/1.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_102_ABPindo/filter.txt -O /root/AdGuardHome/data/filters/2.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_103_BulgarianList/filter.txt -O /root/AdGuardHome/data/filters/3.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_104_EasyListChina/filter.txt -O /root/AdGuardHome/data/filters/4.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_105_EasyListCzechAndSlovak/filter.txt -O /root/AdGuardHome/data/filters/5.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_106_EasyListDutch/filter.txt -O /root/AdGuardHome/data/filters/6.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_107_EasyListGermany/filter.txt -O /root/AdGuardHome/data/filters/7.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_108_EasyListHebrew/filter.txt -O /root/AdGuardHome/data/filters/8.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_109_EasyListItaly/filter.txt -O /root/AdGuardHome/data/filters/9.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_110_EasyListLithuania/filter.txt -O /root/AdGuardHome/data/filters/10.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_111_LatvianList/filter.txt -O /root/AdGuardHome/data/filters/11.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_112_ListeAR/filter.txt -O /root/AdGuardHome/data/filters/12.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_113_ListeFR/filter.txt -O /root/AdGuardHome/data/filters/13.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_114_ROList/filter.txt -O /root/AdGuardHome/data/filters/14.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_115_RUAdList/filter.txt -O /root/AdGuardHome/data/filters/15.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_116_Wiltteri/filter.txt -O /root/AdGuardHome/data/filters/16.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_117_PolishSubFilters/filter.txt -O /root/AdGuardHome/data/filters/17.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_118_EasyPrivacy/filter.txt -O /root/AdGuardHome/data/filters/18.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_119_IcelandicABPList/filter.txt -O /root/AdGuardHome/data/filters/19.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_120_AdBlockID/filter.txt -O /root/AdGuardHome/data/filters/20.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_121_VoidGr/filter.txt -O /root/AdGuardHome/data/filters/21.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_122_FanboysAnnoyances/filter.txt -O /root/AdGuardHome/data/filters/22.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_123_FanboysSocialBlockingList/filter.txt -O /root/AdGuardHome/data/filters/23.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_124_EasyListPortuguese/filter.txt -O /root/AdGuardHome/data/filters/24.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_200_ABPJapaneseFilters/filter.txt -O /root/AdGuardHome/data/filters/25.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_201_WebAnnoyancesUltralist/filter.txt -O /root/AdGuardHome/data/filters/26.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_202_EasyListThailand/filter.txt -O /root/AdGuardHome/data/filters/27.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_203_hufilter/filter.txt -O /root/AdGuardHome/data/filters/28.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_204_PeterLowesList/filter.txt -O /root/AdGuardHome/data/filters/29.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_205_SchacksAdblockPlusListe/filter.txt -O /root/AdGuardHome/data/filters/30.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_206_Xfiles/filter.txt -O /root/AdGuardHome/data/filters/31.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_207_AdblockWarningRemovalList/filter.txt -O /root/AdGuardHome/data/filters/32.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_208_Online_Malicious_URL_Blocklist/filter.txt -O /root/AdGuardHome/data/filters/33.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_209_ADgkMobileChinalist/filter.txt -O /root/AdGuardHome/data/filters/34.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_210_Spam404/filter.txt -O /root/AdGuardHome/data/filters/35.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_211_AntiAdblockKillerReek/filter.txt -O /root/AdGuardHome/data/filters/36.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_212_RUAdListCounters/filter.txt -O /root/AdGuardHome/data/filters/37.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_213_RUAdListBitBlock/filter.txt -O /root/AdGuardHome/data/filters/38.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_214_ABPVNList/filter.txt -O /root/AdGuardHome/data/filters/39.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_215_FanboysEnancedTrackingList/filter.txt -O /root/AdGuardHome/data/filters/40.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_216_PolskiFiltr/filter.txt -O /root/AdGuardHome/data/filters/41.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_217_PolskiFiltrCookies/filter.txt -O /root/AdGuardHome/data/filters/42.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_218_EstonianList/filter.txt -O /root/AdGuardHome/data/filters/43.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_219_ChinaListAndEasyList/filter.txt -O /root/AdGuardHome/data/filters/44.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_220_CJXsAnnoyanceList/filter.txt -O /root/AdGuardHome/data/filters/45.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_221_PolskiFiltrSocial/filter.txt -O /root/AdGuardHome/data/filters/46.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_222_ABPPersian/filter.txt -O /root/AdGuardHome/data/filters/47.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_223_FanboySwedish/filter.txt -O /root/AdGuardHome/data/filters/48.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_225_fanboyAntifacebook/filter.txt -O /root/AdGuardHome/data/filters/49.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_226_FanboyVietnamese/filter.txt -O /root/AdGuardHome/data/filters/50.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_227_List-KR/filter.txt -O /root/AdGuardHome/data/filters/51.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_228_xinggsf/filter.txt -O /root/AdGuardHome/data/filters/52.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_229_IdontCareAboutCookies/filter.txt -O /root/AdGuardHome/data/filters/53.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_230_FanboyEspanol/filter.txt -O /root/AdGuardHome/data/filters/54.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_231_EasyListSpanish/filter.txt -O /root/AdGuardHome/data/filters/55.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_232_KADPrzekrety/filter.txt -O /root/AdGuardHome/data/filters/56.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_233_AdblockListFinland/filter.txt -O /root/AdGuardHome/data/filters/57.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_234_ROList2/filter.txt -O /root/AdGuardHome/data/filters/58.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_235_PersianBlocker/filter.txt -O /root/AdGuardHome/data/filters/59.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_236_ROad-Block/filter.txt -O /root/AdGuardHome/data/filters/60.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_237_PolishAnnoyance/filter.txt -O /root/AdGuardHome/data/filters/61.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_238_PolskiFiltrAdg/filter.txt -O /root/AdGuardHome/data/filters/62.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_239_FanboyAntifonts/filter.txt -O /root/AdGuardHome/data/filters/63.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_240_BarbBlock/filter.txt -O /root/AdGuardHome/data/filters/64.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_241_FanboyCookiemonster/filter.txt -O /root/AdGuardHome/data/filters/65.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_242_NoCoin/filter.txt -O /root/AdGuardHome/data/filters/66.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_243_FrellwitSwedish/filter.txt -O /root/AdGuardHome/data/filters/67.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_244_YousList/filter.txt -O /root/AdGuardHome/data/filters/68.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_245_AlleBlock/filter.txt -O /root/AdGuardHome/data/filters/69.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_246_EasyListPolish/filter.txt -O /root/AdGuardHome/data/filters/70.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_247_PolishRssFilters/filter.txt -O /root/AdGuardHome/data/filters/71.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_249_NorwegianList/filter.txt -O /root/AdGuardHome/data/filters/72.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_250_DandelionSproutAnnoyances/filter.txt -O /root/AdGuardHome/data/filters/73.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_251_LegitimateURLShortener/filter.txt -O /root/AdGuardHome/data/filters/74.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_252_DandelionSproutSerboCroatian/filter.txt -O /root/AdGuardHome/data/filters/75.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_253_IndianList/filter.txt -O /root/AdGuardHome/data/filters/76.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_254_MacedonianadBlockFilters/filter.txt -O /root/AdGuardHome/data/filters/77.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_255_Phishing_URL_Blocklist/filter.txt -O /root/AdGuardHome/data/filters/78.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_256_Scam_Blocklist/filter.txt -O /root/AdGuardHome/data/filters/79.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_257_uBlock_Origin_Badware_risks/filter.txt -O /root/AdGuardHome/data/filters/80.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_10_Useful/filter.txt -O /root/AdGuardHome/data/filters/81.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt -O /root/AdGuardHome/data/filters/82.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_12_Safari/filter.txt -O /root/AdGuardHome/data/filters/83.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_13_Turkish/filter.txt -O /root/AdGuardHome/data/filters/84.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt -O /root/AdGuardHome/data/filters/85.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt -O /root/AdGuardHome/data/filters/86.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_16_French/filter.txt -O /root/AdGuardHome/data/filters/87.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt -O /root/AdGuardHome/data/filters/88.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_18_Annoyances_Cookies/filter.txt -O /root/AdGuardHome/data/filters/89.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_19_Annoyances_Popups/filter.txt -O /root/AdGuardHome/data/filters/90.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt -O /root/AdGuardHome/data/filters/91.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_20_Annoyances_MobileApp/filter.txt -O /root/AdGuardHome/data/filters/92.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_21_Annoyances_Other/filter.txt -O /root/AdGuardHome/data/filters/93.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt -O /root/AdGuardHome/data/filters/94.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_22_Annoyances_Widgets/filter.txt -O /root/AdGuardHome/data/filters/95.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_23_Ukrainian/filter.txt -O /root/AdGuardHome/data/filters/96.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_24_QuickFixes/filter.txt -O /root/AdGuardHome/data/filters/97.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt -O /root/AdGuardHome/data/filters/98.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt -O /root/AdGuardHome/data/filters/99.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_4_Social/filter.txt -O /root/AdGuardHome/data/filters/100.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_5_Experimental/filter.txt -O /root/AdGuardHome/data/filters/101.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_6_German/filter.txt -O /root/AdGuardHome/data/filters/102.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_7_Japanese/filter.txt -O /root/AdGuardHome/data/filters/103.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_8_Dutch/filter.txt -O /root/AdGuardHome/data/filters/104.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_9_Spanish/filter.txt -O /root/AdGuardHome/data/filters/105.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_258_Block_Outsider_Intrusion_into_LAN/filter.txt -O /root/AdGuardHome/data/filters/106.txt
wget https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_259_Dandelion_Sprout's_Anti-Malware_List/filter.txt -O /root/AdGuardHome/data/filters/107.txt
}

_INSTALL
